import type {
  User, PatientProfile, Prescription, Report, Consultation, Vaccination,
  AccessRequest, Permission, Notification, AuditEvent, SecurityEvent,
  EmergencyProfile, MedicationLog, HealthPassport, AnomalyDetection
} from '@/types';

// ── Demo Users ──────────────────────────────────────────────────────────────
export const DEMO_USERS: User[] = [
  {
    id: 'patient-001',
    name: 'Kaviya Ramasamy',
    email: 'kaviya@demo.com',
    role: 'PATIENT',
    patientId: 'patient-001',
    avatar: 'KR',
  },
  {
    id: 'doctor-001',
    name: 'Dr. Arjun Sharma',
    email: 'arjun@demo.com',
    role: 'DOCTOR',
    specialization: 'General Physician',
    organization: 'Apollo Hospitals',
    avatar: 'AS',
  },
  {
    id: 'pharmacy-001',
    name: 'MedPlus Pharmacy',
    email: 'pharmacy@demo.com',
    role: 'PHARMACY',
    organization: 'MedPlus Pharmacy Chain',
    avatar: 'MP',
  },
  {
    id: 'hospital-001',
    name: 'Apollo Hospitals',
    email: 'hospital@demo.com',
    role: 'HOSPITAL',
    organization: 'Apollo Hospitals Chennai',
    avatar: 'AH',
  },
  {
    id: 'lab-001',
    name: 'SRL Diagnostics',
    email: 'lab@demo.com',
    role: 'LAB',
    organization: 'SRL Diagnostics',
    avatar: 'SL',
  },
  {
    id: 'insurance-001',
    name: 'Star Health Insurance',
    email: 'insurance@demo.com',
    role: 'INSURANCE',
    organization: 'Star Health Insurance',
    avatar: 'SH',
  },
  {
    id: 'admin-001',
    name: 'Security Admin',
    email: 'admin@demo.com',
    role: 'SECURITY_ADMIN',
    organization: 'MEDIGUARD X Platform',
    avatar: 'SA',
  },
];

// ── Patient Profile ──────────────────────────────────────────────────────────
export const PATIENT_PROFILE: PatientProfile = {
  userId: 'patient-001',
  bloodGroup: 'O+',
  allergies: ['Penicillin', 'Sulfa drugs', 'Shellfish'],
  criticalMedications: ['Metformin 500mg', 'Atorvastatin 10mg'],
  emergencyContact: 'Ravi Ramasamy (Father)',
  emergencyPhone: '+91 98765 43210',
  dateOfBirth: '1992-06-15',
  gender: 'Female',
  address: '42, Anna Nagar, Chennai – 600040',
  insuranceId: 'STAR-2024-88412',
};

// ── Prescriptions ────────────────────────────────────────────────────────────
export const PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx-001',
    patientId: 'patient-001',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Arjun Sharma',
    medicine: 'Metformin',
    dosage: '500mg',
    frequency: 'Twice daily',
    duration: '90 days',
    date: '2026-08-01',
    status: 'ACTIVE',
    diagnosis: 'Type 2 Diabetes Management',
    drugClass: 'Biguanides',
    notes: 'Take with food to reduce GI side effects',
    aiChecked: true,
    aiRisk: 'LOW',
  },
  {
    id: 'rx-002',
    patientId: 'patient-001',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Arjun Sharma',
    medicine: 'Atorvastatin',
    dosage: '10mg',
    frequency: 'Once daily at night',
    duration: '90 days',
    date: '2026-08-01',
    status: 'ACTIVE',
    diagnosis: 'Hypercholesterolemia',
    drugClass: 'Statins',
    notes: 'Preferably taken in the evening',
    aiChecked: true,
    aiRisk: 'LOW',
  },
  {
    id: 'rx-003',
    patientId: 'patient-001',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Arjun Sharma',
    medicine: 'Amoxicillin',
    dosage: '500mg',
    frequency: 'Three times daily',
    duration: '7 days',
    date: '2026-07-15',
    status: 'COMPLETED',
    diagnosis: 'Bacterial throat infection',
    drugClass: 'Penicillin Antibiotics',
    notes: 'ALLERGY FLAGGED — verify with patient',
    aiChecked: true,
    aiRisk: 'HIGH',
  },
  {
    id: 'rx-004',
    patientId: 'patient-001',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Arjun Sharma',
    medicine: 'Glipizide',
    dosage: '5mg',
    frequency: 'Once daily before breakfast',
    duration: '30 days',
    date: '2026-08-20',
    status: 'ACTIVE',
    diagnosis: 'Type 2 Diabetes — add-on therapy',
    drugClass: 'Sulfonylureas',
    notes: 'Monitor blood sugar levels closely',
    aiChecked: false,
    aiRisk: 'MEDIUM',
  },
  {
    id: 'rx-005',
    patientId: 'patient-001',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Priya Nair',
    medicine: 'Metformin',
    dosage: '1000mg',
    frequency: 'Twice daily',
    duration: '60 days',
    date: '2026-08-15',
    status: 'ACTIVE',
    diagnosis: 'Type 2 Diabetes — dose increase',
    drugClass: 'Biguanides',
    notes: 'Duplicate Metformin prescription detected',
    aiChecked: true,
    aiRisk: 'HIGH',
  },
];

// ── Reports ──────────────────────────────────────────────────────────────────
export const REPORTS: Report[] = [
  {
    id: 'rpt-001',
    patientId: 'patient-001',
    name: 'Complete Blood Count (CBC)',
    type: 'Blood Test',
    provider: 'SRL Diagnostics',
    date: '2026-08-25',
    status: 'NORMAL',
    summary: 'All CBC parameters within normal range. Haemoglobin 13.2 g/dL.',
    findings: 'WBC: 7,200/μL (N), RBC: 4.8M/μL (N), Haemoglobin: 13.2 g/dL (N), Platelets: 280,000/μL (N)',
    hash: 'a3f5c2d1e8b4a7f6',
  },
  {
    id: 'rpt-002',
    patientId: 'patient-001',
    name: 'HbA1c (Glycated Haemoglobin)',
    type: 'Blood Test',
    provider: 'Apollo Diagnostics',
    date: '2026-08-20',
    status: 'ABNORMAL',
    summary: 'HbA1c at 7.8% — slightly above target. Review diabetes management plan.',
    findings: 'HbA1c: 7.8% (Target <7.0%), Fasting glucose: 142 mg/dL (Slightly elevated)',
    hash: 'b7e3a9c4f2d6e1a8',
  },
  {
    id: 'rpt-003',
    patientId: 'patient-001',
    name: 'Lipid Profile',
    type: 'Blood Test',
    provider: 'Thyrocare',
    date: '2026-07-30',
    status: 'ABNORMAL',
    summary: 'LDL cholesterol elevated at 142 mg/dL. Statin therapy recommended.',
    findings: 'Total Cholesterol: 218 mg/dL (Borderline), LDL: 142 mg/dL (High), HDL: 52 mg/dL (N), TG: 168 mg/dL (N)',
    hash: 'c1f7b3e5a2d8f4c6',
  },
  {
    id: 'rpt-004',
    patientId: 'patient-001',
    name: 'Chest X-Ray',
    type: 'Radiology',
    provider: 'Apollo Hospitals',
    date: '2026-06-15',
    status: 'NORMAL',
    summary: 'No active cardiopulmonary disease. Heart size normal. Lungs clear.',
    findings: 'Lung fields: Clear, Heart size: Normal, Mediastinum: Normal width, No pleural effusion',
    hash: 'd9e2c6f1a4b7e3d5',
  },
  {
    id: 'rpt-005',
    patientId: 'patient-001',
    name: 'Urine Routine',
    type: 'Urinalysis',
    provider: 'SRL Diagnostics',
    date: '2026-08-25',
    status: 'NORMAL',
    summary: 'Urinalysis within normal limits. No proteinuria or glucosuria.',
    findings: 'pH: 6.0, Protein: Nil, Glucose: Nil, RBCs: Nil, WBCs: 0-2/HPF',
    hash: 'e4c8a1f6b2d9e7c3',
  },
];

// ── Consultations ────────────────────────────────────────────────────────────
export const CONSULTATIONS: Consultation[] = [
  {
    id: 'con-001',
    patientId: 'patient-001',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Arjun Sharma',
    specialization: 'General Physician',
    date: '2026-08-01',
    diagnosis: 'Type 2 Diabetes Mellitus, Hypercholesterolemia',
    notes: 'Patient presents with controlled diabetes. HbA1c slightly elevated. Adjusted Metformin dosage and added statin for cholesterol management. Dietary counselling provided.',
    followUp: '2026-09-01',
    status: 'COMPLETED',
  },
  {
    id: 'con-002',
    patientId: 'patient-001',
    doctorId: 'doctor-002',
    doctorName: 'Dr. Lakshmi Iyer',
    specialization: 'Endocrinologist',
    date: '2026-07-10',
    diagnosis: 'Hypothyroidism monitoring',
    notes: 'TSH within normal range. Continue current thyroid medication. Annual thyroid function test scheduled.',
    followUp: '2027-01-10',
    status: 'COMPLETED',
  },
  {
    id: 'con-003',
    patientId: 'patient-001',
    doctorId: 'doctor-003',
    doctorName: 'Dr. Karthik Menon',
    specialization: 'Ophthalmologist',
    date: '2026-06-20',
    diagnosis: 'Annual diabetic eye screening — No retinopathy',
    notes: 'Fundoscopy shows no signs of diabetic retinopathy. Vision 6/6 bilateral. Next screening in 12 months.',
    followUp: '2027-06-20',
    status: 'COMPLETED',
  },
  {
    id: 'con-004',
    patientId: 'patient-001',
    doctorId: 'doctor-001',
    doctorName: 'Dr. Arjun Sharma',
    specialization: 'General Physician',
    date: '2026-09-15',
    diagnosis: 'Scheduled follow-up',
    notes: 'Review HbA1c and lipid profile. Medication review.',
    status: 'SCHEDULED',
  },
];

// ── Vaccinations ─────────────────────────────────────────────────────────────
export const VACCINATIONS: Vaccination[] = [
  {
    id: 'vax-001',
    patientId: 'patient-001',
    vaccine: 'COVID-19 (Covishield)',
    date: '2021-06-15',
    provider: 'Apollo Hospitals',
    dose: 'Dose 1 of 2',
    batchNumber: 'CV-2021-0615-A',
  },
  {
    id: 'vax-002',
    patientId: 'patient-001',
    vaccine: 'COVID-19 (Covishield)',
    date: '2021-09-10',
    provider: 'Apollo Hospitals',
    dose: 'Dose 2 of 2',
    batchNumber: 'CV-2021-0910-B',
  },
  {
    id: 'vax-003',
    patientId: 'patient-001',
    vaccine: 'Influenza (Fluarix)',
    date: '2026-01-20',
    provider: 'Primary Health Centre',
    dose: 'Annual',
    nextDue: '2027-01-20',
    batchNumber: 'FLU-2026-0120',
  },
  {
    id: 'vax-004',
    patientId: 'patient-001',
    vaccine: 'Hepatitis B',
    date: '2020-03-15',
    provider: 'SRL Diagnostics',
    dose: 'Booster',
    batchNumber: 'HBV-2020-0315',
  },
];

// ── Access Requests ──────────────────────────────────────────────────────────
export const ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: 'req-001',
    requesterId: 'pharmacy-001',
    requesterName: 'MedPlus Pharmacy',
    requesterOrg: 'MedPlus Pharmacy Chain',
    requesterRole: 'PHARMACY',
    patientId: 'patient-001',
    purpose: 'Prescription dispensing — verify current medications before dispensing new prescription',
    requestedFields: ['medicine', 'dosage', 'frequency', 'prescriptionDate', 'doctorName', 'duration', 'diagnosis', 'allergies', 'bloodGroup', 'insuranceId', 'consultationNotes', 'labReports'],
    requestDate: '2026-09-01T09:00:00Z',
    expiryDate: '2026-09-02T09:00:00Z',
    status: 'PENDING',
    notes: 'Patient presented prescription at counter. Verification needed.',
  },
  {
    id: 'req-002',
    requesterId: 'insurance-001',
    requesterName: 'Star Health Insurance',
    requesterOrg: 'Star Health Insurance',
    requesterRole: 'INSURANCE',
    patientId: 'patient-001',
    purpose: 'Insurance claim verification — diabetes treatment claim processing',
    requestedFields: ['diagnosis', 'consultationNotes', 'labReports', 'prescriptions', 'hospitalRecords', 'bloodGroup', 'allergies', 'medicine', 'dosage'],
    requestDate: '2026-08-28T14:00:00Z',
    expiryDate: '2026-09-04T14:00:00Z',
    status: 'PENDING',
    notes: 'Claim #CLM-2026-4521 for diabetes management treatment.',
  },
  {
    id: 'req-003',
    requesterId: 'doctor-001',
    requesterName: 'Dr. Arjun Sharma',
    requesterOrg: 'Apollo Hospitals',
    requesterRole: 'DOCTOR',
    patientId: 'patient-001',
    purpose: 'Follow-up consultation — review lab results and adjust treatment plan',
    requestedFields: ['labReports', 'prescriptions', 'consultationNotes', 'bloodGroup'],
    requestDate: '2026-08-25T10:00:00Z',
    expiryDate: '2026-09-15T10:00:00Z',
    status: 'APPROVED',
    notes: 'Routine follow-up access.',
  },
  {
    id: 'req-004',
    requesterId: 'lab-001',
    requesterName: 'SRL Diagnostics',
    requesterOrg: 'SRL Diagnostics',
    requesterRole: 'LAB',
    patientId: 'patient-001',
    purpose: 'Lab test order verification — confirm doctor order before processing',
    requestedFields: ['labOrders', 'prescriptions', 'diagnosis'],
    requestDate: '2026-08-20T08:00:00Z',
    expiryDate: '2026-08-21T08:00:00Z',
    status: 'REJECTED',
    notes: 'Patient declined additional lab information sharing.',
  },
  {
    id: 'req-005',
    requesterId: 'hospital-001',
    requesterName: 'Apollo Hospitals',
    requesterOrg: 'Apollo Hospitals Chennai',
    requesterRole: 'HOSPITAL',
    patientId: 'patient-001',
    purpose: 'Pre-admission record review for scheduled procedure',
    requestedFields: ['allergies', 'criticalMedications', 'bloodGroup', 'consultationNotes', 'labReports'],
    requestDate: '2026-08-10T11:00:00Z',
    expiryDate: '2026-08-17T11:00:00Z',
    status: 'EXPIRED',
    notes: 'Admission was postponed.',
  },
];

// ── Permissions ──────────────────────────────────────────────────────────────
export const PERMISSIONS: Permission[] = [
  {
    id: 'perm-001',
    requestId: 'req-003',
    patientId: 'patient-001',
    grantedTo: 'doctor-001',
    grantedToName: 'Dr. Arjun Sharma',
    grantedToOrg: 'Apollo Hospitals',
    grantedToRole: 'DOCTOR',
    purpose: 'Follow-up consultation — review lab results',
    allowedFields: ['labReports', 'prescriptions', 'consultationNotes', 'bloodGroup'],
    restrictedFields: ['allergies', 'insuranceId', 'emergencyContact', 'diagnosis', 'medicine', 'dosage'],
    grantedAt: '2026-08-25T11:00:00Z',
    expiresAt: '2026-09-15T10:00:00Z',
    status: 'ACTIVE',
  },
  {
    id: 'perm-002',
    requestId: 'perm-prev-001',
    patientId: 'patient-001',
    grantedTo: 'pharmacy-001',
    grantedToName: 'MedPlus Pharmacy',
    grantedToOrg: 'MedPlus Pharmacy Chain',
    grantedToRole: 'PHARMACY',
    purpose: 'Prescription dispensing — previous visit',
    allowedFields: ['medicine', 'dosage', 'prescriptionDate'],
    restrictedFields: ['diagnosis', 'consultationNotes', 'labReports', 'allergies', 'bloodGroup', 'insuranceId', 'frequency', 'duration', 'doctorName'],
    grantedAt: '2026-08-15T09:00:00Z',
    expiresAt: '2026-08-16T09:00:00Z',
    status: 'EXPIRED',
  },
  {
    id: 'perm-003',
    requestId: 'perm-prev-002',
    patientId: 'patient-001',
    grantedTo: 'lab-001',
    grantedToName: 'SRL Diagnostics',
    grantedToOrg: 'SRL Diagnostics',
    grantedToRole: 'LAB',
    purpose: 'Blood test authorization',
    allowedFields: ['labOrders', 'diagnosis'],
    restrictedFields: ['prescriptions', 'consultationNotes', 'bloodGroup', 'allergies', 'medicine', 'dosage'],
    grantedAt: '2026-08-10T10:00:00Z',
    expiresAt: '2026-08-11T10:00:00Z',
    status: 'REVOKED',
  },
];

// ── Notifications ────────────────────────────────────────────────────────────
export const NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    userId: 'patient-001',
    type: 'ACCESS_REQUEST',
    title: 'New Access Request',
    message: 'MedPlus Pharmacy has requested access to your prescription data for dispensing purposes.',
    timestamp: '2026-09-01T09:05:00Z',
    read: false,
    relatedId: 'req-001',
    severity: 'INFO',
  },
  {
    id: 'notif-002',
    userId: 'patient-001',
    type: 'ACCESS_REQUEST',
    title: 'Insurance Data Request',
    message: 'Star Health Insurance has requested access to your medical records for claim #CLM-2026-4521.',
    timestamp: '2026-08-28T14:10:00Z',
    read: false,
    relatedId: 'req-002',
    severity: 'WARNING',
  },
  {
    id: 'notif-003',
    userId: 'patient-001',
    type: 'SECURITY_ALERT',
    title: 'Unauthorized Access Blocked',
    message: 'An attempt to access your complete medical record without authorization was blocked and audited.',
    timestamp: '2026-08-27T16:30:00Z',
    read: false,
    relatedId: 'sec-004',
    severity: 'ERROR',
  },
  {
    id: 'notif-004',
    userId: 'patient-001',
    type: 'PERMISSION_GRANTED',
    title: 'Access Approved',
    message: "You approved Dr. Arjun Sharma's access to your lab reports and consultation notes until Sep 15.",
    timestamp: '2026-08-25T11:05:00Z',
    read: true,
    relatedId: 'perm-001',
    severity: 'SUCCESS',
  },
  {
    id: 'notif-005',
    userId: 'patient-001',
    type: 'AI_WARNING',
    title: 'AI Safety Alert',
    message: 'Possible duplicate Metformin prescription detected. Rx-005 may conflict with Rx-001. Please review.',
    timestamp: '2026-08-20T15:00:00Z',
    read: false,
    relatedId: 'rx-005',
    severity: 'WARNING',
  },
  {
    id: 'notif-006',
    userId: 'patient-001',
    type: 'PERMISSION_EXPIRED',
    title: 'Permission Expired',
    message: "MedPlus Pharmacy's access to your prescription data has expired after 24 hours.",
    timestamp: '2026-08-16T09:00:00Z',
    read: true,
    relatedId: 'perm-002',
    severity: 'INFO',
  },
  {
    id: 'notif-007',
    userId: 'patient-001',
    type: 'PERMISSION_REVOKED',
    title: 'Access Revoked',
    message: "You revoked SRL Diagnostics' access to your lab information.",
    timestamp: '2026-08-10T12:00:00Z',
    read: true,
    relatedId: 'perm-003',
    severity: 'WARNING',
  },
  {
    id: 'notif-008',
    userId: 'patient-001',
    type: 'SYSTEM',
    title: 'Health Passport Generated',
    message: 'Your secure health passport QR code has been generated and is valid for 30 days.',
    timestamp: '2026-08-05T10:00:00Z',
    read: true,
    severity: 'SUCCESS',
  },
];

// ── Audit Events ─────────────────────────────────────────────────────────────
export const AUDIT_EVENTS: AuditEvent[] = [
  {
    id: 'audit-001',
    actorId: 'patient-001',
    actorName: 'Kaviya Ramasamy',
    actorRole: 'PATIENT',
    action: 'PERMISSION_GRANTED',
    target: 'Dr. Arjun Sharma',
    targetId: 'perm-001',
    result: 'SUCCESS',
    timestamp: '2026-08-25T11:05:00Z',
    fieldsAccessed: ['labReports', 'prescriptions', 'consultationNotes', 'bloodGroup'],
    reason: 'Follow-up consultation access approved',
    ipAddress: '192.168.1.10',
    previousHash: '0000000000000000',
    currentHash: 'a1b2c3d4e5f60001',
  },
  {
    id: 'audit-002',
    actorId: 'insurance-001',
    actorName: 'Star Health Insurance',
    actorRole: 'INSURANCE',
    action: 'ACCESS_BLOCKED',
    target: 'Patient Medical Records',
    targetId: 'patient-001',
    result: 'BLOCKED',
    timestamp: '2026-08-27T16:28:00Z',
    reason: 'No active permission. Patient consent not granted.',
    ipAddress: '203.45.67.89',
    previousHash: 'a1b2c3d4e5f60001',
    currentHash: 'b2c3d4e5f6a70002',
  },
  {
    id: 'audit-003',
    actorId: 'pharmacy-001',
    actorName: 'MedPlus Pharmacy',
    actorRole: 'PHARMACY',
    action: 'ACCESS_REQUESTED',
    target: 'Prescription Data',
    targetId: 'req-001',
    result: 'SUCCESS',
    timestamp: '2026-09-01T09:00:00Z',
    reason: 'Prescription dispensing verification',
    ipAddress: '10.0.1.45',
    previousHash: 'b2c3d4e5f6a70002',
    currentHash: 'c3d4e5f6a7b80003',
  },
  {
    id: 'audit-004',
    actorId: 'patient-001',
    actorName: 'Kaviya Ramasamy',
    actorRole: 'PATIENT',
    action: 'PERMISSION_REVOKED',
    target: 'SRL Diagnostics',
    targetId: 'perm-003',
    result: 'SUCCESS',
    timestamp: '2026-08-10T12:00:00Z',
    reason: 'Unnecessary access scope — patient revoked',
    ipAddress: '192.168.1.10',
    previousHash: 'c3d4e5f6a7b80003',
    currentHash: 'd4e5f6a7b8c90004',
  },
  {
    id: 'audit-005',
    actorId: 'admin-001',
    actorName: 'Security Admin',
    actorRole: 'SECURITY_ADMIN',
    action: 'ATTACK_SIMULATION',
    target: 'Security System',
    targetId: 'sec-sim-001',
    result: 'BLOCKED',
    timestamp: '2026-08-29T11:00:00Z',
    reason: 'Unauthorized access simulation — BLOCKED by security engine',
    ipAddress: '127.0.0.1',
    previousHash: 'd4e5f6a7b8c90004',
    currentHash: 'e5f6a7b8c9d00005',
  },
  {
    id: 'audit-006',
    actorId: 'doctor-001',
    actorName: 'Dr. Arjun Sharma',
    actorRole: 'DOCTOR',
    action: 'RECORD_ACCESSED',
    target: 'Lab Reports',
    targetId: 'rpt-001',
    result: 'SUCCESS',
    timestamp: '2026-08-26T09:00:00Z',
    fieldsAccessed: ['labReports'],
    reason: 'Authorized access via perm-001',
    ipAddress: '172.16.0.5',
    previousHash: 'e5f6a7b8c9d00005',
    currentHash: 'f6a7b8c9d0e10006',
  },
];

// ── Security Events ──────────────────────────────────────────────────────────
export const SECURITY_EVENTS: SecurityEvent[] = [
  {
    id: 'sec-001',
    type: 'UNAUTHORIZED_ACCESS',
    severity: 'CRITICAL',
    description: 'Insurance company attempted to access full medical record without patient consent',
    actor: 'Star Health Insurance',
    timestamp: '2026-08-27T16:28:00Z',
    blocked: true,
    details: { requestedData: 'Full Medical Record', actualPermission: 'None', action: 'REQUEST_BLOCKED' },
  },
  {
    id: 'sec-002',
    type: 'EXPIRED_PERMISSION',
    severity: 'MEDIUM',
    description: 'MedPlus Pharmacy attempted access with expired permission',
    actor: 'MedPlus Pharmacy',
    timestamp: '2026-08-17T11:00:00Z',
    blocked: true,
    details: { permissionId: 'perm-002', expiredAt: '2026-08-16T09:00:00Z', action: 'ACCESS_DENIED' },
  },
  {
    id: 'sec-003',
    type: 'EXCESSIVE_DATA',
    severity: 'HIGH',
    description: 'Data request exceeded approved field scope — field filter applied',
    actor: 'SRL Diagnostics',
    timestamp: '2026-08-10T10:30:00Z',
    blocked: false,
    details: { requestedFields: 12, approvedFields: 2, action: 'FIELD_FILTERED' },
  },
  {
    id: 'sec-004',
    type: 'SUSPICIOUS_ACCESS',
    severity: 'HIGH',
    description: 'Unusual access pattern detected — multiple rapid requests from insurance IP',
    actor: 'Star Health Insurance',
    timestamp: '2026-08-27T16:25:00Z',
    blocked: true,
    details: { requestsIn5Min: 8, normalThreshold: 2, action: 'RATE_LIMITED' },
  },
  {
    id: 'sec-005',
    type: 'SIMULATION',
    severity: 'LOW',
    description: 'Security Admin ran unauthorized access simulation — threat detection test',
    actor: 'Security Admin',
    timestamp: '2026-08-29T11:00:00Z',
    blocked: true,
    details: { simulationType: 'UNAUTHORIZED_ACCESS', result: 'DETECTED_AND_BLOCKED', auditCreated: true },
  },
];

// ── Emergency Profile ────────────────────────────────────────────────────────
export const EMERGENCY_PROFILE: EmergencyProfile = {
  patientId: 'patient-001',
  bloodGroup: 'O+',
  allergies: ['Penicillin', 'Sulfa drugs', 'Shellfish'],
  criticalMedications: ['Metformin 500mg (Diabetes)', 'Atorvastatin 10mg (Cholesterol)'],
  emergencyContact: 'Ravi Ramasamy (Father)',
  emergencyPhone: '+91 98765 43210',
  medicalAlerts: ['Type 2 Diabetes — monitor blood sugar', 'Penicillin allergy — DO NOT administer', 'Sulfa drug allergy — DO NOT administer'],
  organDonor: true,
  lastUpdated: '2026-08-01T00:00:00Z',
};

// ── Medication Logs ──────────────────────────────────────────────────────────
export const MEDICATION_LOGS: MedicationLog[] = [
  { id: 'med-001', prescriptionId: 'rx-001', patientId: 'patient-001', medicine: 'Metformin 500mg', scheduledTime: '08:00', takenAt: '08:12', status: 'TAKEN', date: '2026-09-01' },
  { id: 'med-002', prescriptionId: 'rx-001', patientId: 'patient-001', medicine: 'Metformin 500mg', scheduledTime: '20:00', status: 'UPCOMING', date: '2026-09-01' },
  { id: 'med-003', prescriptionId: 'rx-002', patientId: 'patient-001', medicine: 'Atorvastatin 10mg', scheduledTime: '21:00', status: 'UPCOMING', date: '2026-09-01' },
  { id: 'med-004', prescriptionId: 'rx-004', patientId: 'patient-001', medicine: 'Glipizide 5mg', scheduledTime: '07:00', status: 'MISSED', date: '2026-09-01' },
  { id: 'med-005', prescriptionId: 'rx-001', patientId: 'patient-001', medicine: 'Metformin 500mg', scheduledTime: '08:00', takenAt: '08:05', status: 'TAKEN', date: '2026-08-31' },
  { id: 'med-006', prescriptionId: 'rx-001', patientId: 'patient-001', medicine: 'Metformin 500mg', scheduledTime: '20:00', takenAt: '20:30', status: 'TAKEN', date: '2026-08-31' },
  { id: 'med-007', prescriptionId: 'rx-002', patientId: 'patient-001', medicine: 'Atorvastatin 10mg', scheduledTime: '21:00', takenAt: '21:15', status: 'TAKEN', date: '2026-08-31' },
];

// ── Health Passport ──────────────────────────────────────────────────────────
export const HEALTH_PASSPORT: HealthPassport = {
  id: 'pass-001',
  patientId: 'patient-001',
  token: 'MGX-2026-KR-A7F3B2E1',
  qrData: 'https://mediguardx.app/verify/MGX-2026-KR-A7F3B2E1',
  generatedAt: '2026-08-05T10:00:00Z',
  expiresAt: '2026-09-05T10:00:00Z',
  status: 'ACTIVE',
  viewCount: 3,
};

// ── Anomaly Detections ────────────────────────────────────────────────────────
export const ANOMALIES: AnomalyDetection[] = [
  {
    id: 'anom-001',
    type: 'DUPLICATE_DRUG_CLASS',
    severity: 'HIGH',
    description: 'Two Biguanide-class medications prescribed simultaneously',
    evidence: 'Rx-001 (Metformin 500mg) and Rx-005 (Metformin 1000mg) — same drug class, different prescribers',
    prescriptionIds: ['rx-001', 'rx-005'],
    detectedAt: '2026-08-20T15:00:00Z',
  },
  {
    id: 'anom-002',
    type: 'REPEATED_PRESCRIPTION',
    severity: 'MEDIUM',
    description: 'Metformin prescribed twice within 15 days by different doctors',
    evidence: 'Dr. Arjun Sharma (Aug 1) and Dr. Priya Nair (Aug 15) — potential coordination issue',
    prescriptionIds: ['rx-001', 'rx-005'],
    detectedAt: '2026-08-20T15:05:00Z',
  },
  {
    id: 'anom-003',
    type: 'UNUSUAL_DOSAGE',
    severity: 'HIGH',
    description: 'Amoxicillin prescribed despite documented Penicillin allergy',
    evidence: 'Patient profile shows Penicillin allergy. Amoxicillin (Rx-003) belongs to Penicillin group.',
    prescriptionIds: ['rx-003'],
    detectedAt: '2026-07-15T09:00:00Z',
  },
];

// ── Translations ─────────────────────────────────────────────────────────────
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    healthVault: 'Health Vault',
    prescriptions: 'Prescriptions',
    reports: 'Reports',
    consultations: 'Consultations',
    vaccinations: 'Vaccinations',
    consentCenter: 'Consent Center',
    activePermissions: 'Active Permissions',
    accessRequests: 'Access Requests',
    privacyFirewall: 'Privacy Firewall',
    emergencyCapsule: 'Emergency Capsule',
    securityCenter: 'Security Command',
    attackLab: 'Attack Lab',
    aiSafety: 'AI Safety',
    fraudDetection: 'Fraud Detection',
    healthPassport: 'Health Passport',
    notifications: 'Notifications',
    auditTrail: 'Audit Trail',
    settings: 'Settings',
    logout: 'Logout',
    approve: 'Approve',
    reject: 'Reject',
    revoke: 'Revoke',
    viewDetails: 'View Details',
    loading: 'Loading...',
    blocked: 'Access Blocked',
    allowed: 'Access Allowed',
    protected: 'Protected',
    healthJourney: 'Health Journey',
    medicationCompanion: 'Medication Companion',
    privacyVerification: 'Privacy Verification',
    search: 'Search',
    activity: 'Activity & Audit',
  },
  ta: {
    dashboard: 'டாஷ்போர்டு',
    healthVault: 'ஆரோக்கிய பூட்டகம்',
    prescriptions: 'மருந்து சீட்டுகள்',
    reports: 'அறிக்கைகள்',
    consultations: 'ஆலோசனைகள்',
    consentCenter: 'ஒப்புதல் மையம்',
    emergencyCapsule: 'அவசர தகவல்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    approve: 'ஒப்புதல்',
    reject: 'நிராகரி',
    revoke: 'திரும்பப் பெறு',
    notifications: 'அறிவிப்புகள்',
    protected: 'பாதுகாக்கப்பட்டது',
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    healthVault: 'स्वास्थ्य तिजोरी',
    prescriptions: 'नुस्खे',
    reports: 'रिपोर्ट',
    consultations: 'परामर्श',
    consentCenter: 'सहमति केंद्र',
    emergencyCapsule: 'आपातकालीन कैप्सूल',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    approve: 'स्वीकृत',
    reject: 'अस्वीकार',
    revoke: 'रद्द करें',
    notifications: 'सूचनाएं',
    protected: 'संरक्षित',
  },
  te: {
    dashboard: 'డాష్‌బోర్డ్',
    healthVault: 'ఆరోగ్య వాల్ట్',
    prescriptions: 'ప్రిస్క్రిప్షన్లు',
    reports: 'నివేదికలు',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగ్ అవుట్',
    notifications: 'నోటిఫికేషన్లు',
    protected: 'రక్షించబడింది',
  },
  ml: {
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    healthVault: 'ആരോഗ്യ വോൾട്ട്',
    prescriptions: 'കുറിപ്പടികൾ',
    reports: 'റിപ്പോർട്ടുകൾ',
    settings: 'ക്രമീകരണങ്ങൾ',
    logout: 'ലോഗ് ഔട്ട്',
    notifications: 'അറിയിപ്പുകൾ',
    protected: 'സംരക്ഷിതം',
  },
  kn: {
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    healthVault: 'ಆರೋಗ್ಯ ವಾಲ್ಟ್',
    prescriptions: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್‌ಗಳು',
    reports: 'ವರದಿಗಳು',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    logout: 'ಲಾಗ್ ಔಟ್',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    protected: 'ಸಂರಕ್ಷಿತ',
  },
};
